export default {
  questions: [
    "Never have i ever killed a soul",
    "Never have i ever hit a women",
    "Never have I ever played hooky from school or work",
    "Never have I ever stolen anything",
    "Never have I ever missed a flight",
    "Never have I ever drunk-dialed my ex",
    "Never have I ever rode a motorcycle",
    "Never have I ever lost a bet",
    "Never have I ever gotten lost alone in a foreign country",
    "Never have I ever bribed someone",
    "Never have I ever gone skinny-dipping",
    "Never have I ever cheated on someone",
    "Never have I ever sang karaoke",
    "Never have I ever broken a bone",
    "Never have I ever lived alone",
    "Never have I ever been on a yacht",
    "Never have I ever been on TV",
    "Never have I ever been on a blind date",
    "Never have I ever lied to law enforcement",
    "Never have I ever gotten a tattoo",
    "Never have I ever used a fake ID",
    "Never have I ever broken up with someone",
    "Never have I ever got seriously hungover",
    "Never have I ever used someone else’s toothbrush",
    "Never have I ever clogged somebody else’s toilet",
    "Never have I ever fallen asleep in public",
    "Never have I ever kissed someone in public",
    "Never have I ever fought in public",
    "Never have I ever dined and dashed",
    "Never have I ever won the lottery",
    "Never have I ever had to go to court",
    "Never have I ever been to a destination wedding",
    "Never have I ever lied to a boss",
    "Never have I ever crashed a wedding",
    "Never have I ever kissed more than one person in 24 hours",
    "Never have I ever pranked someone",
    "Never have I ever had a one-night stand",
    "Never have I ever regifted a gift",
    "Never have I ever trolled someone on social media",
    "Never have I ever climbed out of a window",
    "Never have I ever driven over a curb",
    "Never have I ever laughed so hard I, um, peed my pants as an adult",
    "Never have I ever got on the wrong train or bus",
    "Never have I ever sent a sext",
    "Never have I ever cursed in a place of worship",
    "Never have I ever snooped through someone’s stuff",
    "Never have I ever tried marijuana",
    "Never have I ever gone 24 hours without showering",
    "Never have I ever had to take a walk of shame",
    "Never have I ever gone on a solo vacation",
    "Never have I ever gone on a road trip",
    "Never have I ever ate an entire pizza by myself",
    "Never have I ever saved a life",
    "Never have I ever got a tattoo",
    "Never have I ever wanted to be on a reality TV show",
    "Never have I ever started a fire",
    "Never have I ever gotten stopped by airport security",
    "Never have I ever gone viral online",
    "Never have I ever left gum in a public space",
    "Never have I ever slept outdoors for an entire night",
    "Never have I ever ran a marathon",
    "Never have I ever given/received a lap dance",
    "Never have I ever made a speech in front of 100 people or more",
    "Never have I ever relieved myself in a public pool",
    "Never have I ever lied to my best friend about who I was with",
    "Never have I ever been to a Disney park",
    "Never have I ever had a threesome",
    "Never have I ever left someone on read",
    "Never have I ever fallen asleep during sex",
    "Never have I ever lied about my age",
    "Never have I ever made up a story about someone who wasn’t real",
    "Never have I ever believed something was haunted",
    "Never have I ever participated in a protest",
    "Never have I ever had sleep paralysis",
    "Never have I ever been the alibi for a lying friend",
    "Never have I ever pulled an all-nighter",
    "Never have I ever role-played",
    "Never have I ever regretted an apology",
    "Never have I ever pretended I was sick for attention",
    "Never have I ever disliked something that I cooked",
    "Never have I ever deleted a post on social media because it didn’t get enough likes",
    "Never have I ever spent more than $100 on a top",
    "Never have I ever thrown a drink at someone",
    "Never have I ever worn someone else’s underwear",
    "Never have I ever traveled to Europe",
    "Never have I ever attempted a trendy diet",
    "Never have I ever gone to a strip club",
    "Never have I ever binged an entire series in one day",
    "Never have I ever tried psychedelics",
    "Never have I ever met someone famous",
    "Never have I ever gone streaking",
    "Never have I ever been on a sports team",
    "Never have I ever maxed out a credit card",
    "Never have I ever been blackout drunk",
    "Never have I ever been engaged",
    "Never have I ever gotten married",
    "Never have I ever donated to a charity",
    "Never have I ever pretended to be sick to get out of something",
    "Never have I ever stood up a date",
    "Never have I ever ghosted someone",
    "Never have I ever had sex on a beach",
    "Never have I ever fallen in love",
  ],
};
